### ISSUE TITLE
catkin build error

### ISSUE THREAD

**Issue by Wayne-xixi** [ayushgaud/path_planning#12]
Hello, I got some errors when catkin build this project. I use ros-kinetic in ubuntu 16.04 and fcl-0.5 and ros-Octomap. 

`Errors     << path_planning:make /home/fapsros/catkin_ws/logs/path_planning/build.make.018.log                                                                                                             
CMakeFiles/path_planning.dir/src/path_planning.cpp.o: In function `fcl::Transform3f::transform(fcl::Vec3fX<fcl::details::Vec3Data<double> > const&) const':
path_planning.cpp:(.text._ZNK3fcl11Transform3f9transformERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE[_ZNK3fcl11Transform3f9transformERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE]+0x46): undefined reference to `fcl::Quaternion3f::transform(fcl::Vec3fX<fcl::details::Vec3Data<double> > const&) const'
CMakeFiles/path_planning.dir/src/path_planning.cpp.o: In function `fcl::CollisionGeometry::CollisionGeometry()':
path_planning.cpp:(.text._ZN3fcl17CollisionGeometryC2Ev[_ZN3fcl17CollisionGeometryC5Ev]+0x34): undefined reference to `fcl::AABB::AABB()'
CMakeFiles/path_planning.dir/src/path_planning.cpp.o: In function `fcl::CollisionObject::CollisionObject(std::shared_ptr<fcl::CollisionGeometry> const&)':
path_planning.cpp:(.text._ZN3fcl15CollisionObjectC2ERKSt10shared_ptrINS_17CollisionGeometryEE[_ZN3fcl15CollisionObjectC5ERKSt10shared_ptrINS_17CollisionGeometryEE]+0x59): undefined reference to `fcl::AABB::AABB()'
CMakeFiles/path_planning.dir/src/path_planning.cpp.o: In function `fcl::Box::Box(double, double, double)':
path_planning.cpp:(.text._ZN3fcl3BoxC2Eddd[_ZN3fcl3BoxC5Eddd]+0x29): undefined reference to `vtable for fcl::Box'
CMakeFiles/path_planning.dir/src/path_planning.cpp.o: In function `planner::isStateValid(ompl::base::State const*)':
path_planning.cpp:(.text._ZN7planner12isStateValidEPKN4ompl4base5StateE[_ZN7planner12isStateValidEPKN4ompl4base5StateE]+0x1e5): undefined reference to `fcl::collide(fcl::CollisionObject const*, fcl::CollisionObject const*, fcl::CollisionRequest const&, fcl::CollisionResult&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/fapsros/catkin_ws/devel/.private/path_planning/lib/path_planning/path_planning] Error 1
make[1]: *** [CMakeFiles/path_planning.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::Transform3f::transform(fcl::Vec3fX<fcl::details::Vec3Data<double> > const&) const':
path_planning.cpp:(.text._ZNK3fcl11Transform3f9transformERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE[_ZNK3fcl11Transform3f9transformERKNS_6Vec3fXINS_7details8Vec3DataIdEEEE]+0x46): undefined reference to `fcl::Quaternion3f::transform(fcl::Vec3fX<fcl::details::Vec3Data<double> > const&) const'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::CollisionGeometry::CollisionGeometry()':
path_planning.cpp:(.text._ZN3fcl17CollisionGeometryC2Ev[_ZN3fcl17CollisionGeometryC5Ev]+0x34): undefined reference to `fcl::AABB::AABB()'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::CollisionObject::CollisionObject(std::shared_ptr<fcl::CollisionGeometry> const&)':
path_planning.cpp:(.text._ZN3fcl15CollisionObjectC2ERKSt10shared_ptrINS_17CollisionGeometryEE[_ZN3fcl15CollisionObjectC5ERKSt10shared_ptrINS_17CollisionGeometryEE]+0x59): undefined reference to `fcl::AABB::AABB()'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `fcl::Box::Box(double, double, double)':
path_planning.cpp:(.text._ZN3fcl3BoxC2Eddd[_ZN3fcl3BoxC5Eddd]+0x29): undefined reference to `vtable for fcl::Box'
CMakeFiles/path_planning_node.dir/src/path_planning.cpp.o: In function `planner::isStateValid(ompl::base::State const*)':
path_planning.cpp:(.text._ZN7planner12isStateValidEPKN4ompl4base5StateE[_ZN7planner12isStateValidEPKN4ompl4base5StateE]+0x1e5): undefined reference to `fcl::collide(fcl::CollisionObject const*, fcl::CollisionObject const*, fcl::CollisionRequest const&, fcl::CollisionResult&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/fapsros/catkin_ws/devel/.private/path_planning/lib/path_planning/path_planning_node] Error 1
make[1]: *** [CMakeFiles/path_planning_node.dir/all] Error 2
make: *** [all] Error 2
`
looking forward to some help! Thanks.

**Comment by ayushgaud** [comment]
Can you please share the output of this ```pkg-config fcl --modversion```?

Also, I have added a new branch if you prefer using fcl-0.6.0

**Comment by Wayne-xixi** [comment]
@ayushgaud Thank you for the replying! Its really very nice of you! And the output of '''pkg-config fcl --modversion''' is 0.6.0.

**Comment by Wayne-xixi** [comment]
@ayushgaud Is the new branch for fcl 0.6.0 finished?

**Comment by Wayne-xixi** [comment]
solved by rewrite the code with fcl 0.6.0.
