### ISSUE TITLE
Negative position values

### ISSUE THREAD

**Issue by minotauros13** [ayushgaud/path_planning#16]
I am looking into your implementation for a project I currently work on. It works fine, but I recently noticed that the planner does not work for negative values in either of the (x, y, z) positions. I was wondering whether you can hint as to why this may be happening in order to look into it further and possibly correct it?

**Comment by Wayne-xixi** [comment]
> I am looking into your implementation for a project I currently work on. It works fine, but I recently noticed that the planner does not work for negative values in either of the (x, y, z) positions. I was wondering whether you can hint as to why this may be happening in order to look into it further and possibly correct it?

I think you can try to change the state space setBounds.

**Comment by minotauros13** [comment]
As per @Wayne-xixi comment the "bounds" in setBounds() can be set to a negative value
